apiVersion: v1
kind: Service
metadata:
  name: crm-svc-lb
  namespace: book-store-ns
spec:
  type: LoadBalancer
  selector:
    app: crm-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
