apiVersion: v1
kind: Service
metadata:
  name: customer-bff-lb
  namespace: book-store-ns
spec:
  type: LoadBalancer
  selector:
    app: customer-bff
  ports:
    - protocol: TCP
      port: 80
      targetPort: 49160
