apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-svc
  namespace: book-store-ns
spec:
  selector:
    matchLabels:
      app: book-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: book-svc
    spec:
      containers:
        - name: book-svc
          image: ljx02263/book-svc:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: state-volume
              mountPath: /app/state
      volumes:
        - name: state-volume
          emptyDir: {}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - book-svc
